all : Abstraite Binaire Unaire Plus Mult Cos Sin Var Const

Abstraite : javac ExpAbstraite.java
Binaire : javac ExpBinaire.java
Unaire :javac ExpUnaire.java
Plus : javac BinairePlus.java
Mult : javac Binaire Mult.java
Cos: javac UnaireCos.java
Sin : javac UnaireSin.java
Var : javac Variable.java
Const : javac Constante.java
